"""add_body_measurements

Revision ID: 208dbc533322
Revises: add_program_group_to_plans
Create Date: 2026-08-06 14:15:58.051070

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '208dbc533322'
down_revision: Union[str, Sequence[str], None] = 'add_program_group_to_plans'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('body_measurements',
    sa.Column('id', sa.TEXT(), nullable=False),
    sa.Column('profile_id', sa.TEXT(), nullable=False),
    sa.Column('date', sa.DateTime(), nullable=False),
    sa.Column('type', sa.String(length=10), nullable=False),
    sa.Column('goal', sa.String(length=20), nullable=True),
    sa.Column('weight', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('waist', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('narrow_waist', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('chest', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('hips', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('left_arm', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('right_arm', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('left_thigh', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('right_thigh', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('neck', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('body_fat', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('conditions', sa.JSON(), nullable=True),
    sa.Column('front_photo', sa.Text(), nullable=True),
    sa.Column('side_photo', sa.Text(), nullable=True),
    sa.Column('back_photo', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('body_measurements', schema=None) as batch_op:
        batch_op.create_index('ix_body_measurements_profile_date', ['profile_id', 'date'], unique=False)
        batch_op.create_index(batch_op.f('ix_body_measurements_profile_id'), ['profile_id'], unique=False)

    with op.batch_alter_table('workout_plans', schema=None) as batch_op:
        batch_op.alter_column('program_group_id',
               existing_type=sa.VARCHAR(length=36),
               type_=sa.TEXT(),
               existing_nullable=True)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('workout_plans', schema=None) as batch_op:
        batch_op.alter_column('program_group_id',
               existing_type=sa.TEXT(),
               type_=sa.VARCHAR(length=36),
               existing_nullable=True)

    with op.batch_alter_table('body_measurements', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_body_measurements_profile_id'))
        batch_op.drop_index('ix_body_measurements_profile_date')

    op.drop_table('body_measurements')
    # ### end Alembic commands ###
