"""initial schema

Revision ID: 9766ac66abfe
Revises: 
Create Date: 2026-07-25 17:04:27.786918

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9766ac66abfe'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('exercises',
    sa.Column('id', sa.TEXT(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('primary_muscle', sa.String(length=100), nullable=True),
    sa.Column('secondary_muscles', sa.String(length=255), nullable=True),
    sa.Column('equipment', sa.String(length=100), nullable=True),
    sa.Column('movement_pattern', sa.String(length=100), nullable=True),
    sa.Column('difficulty', sa.String(length=50), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('aliases', sa.JSON(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    with op.batch_alter_table('exercises', schema=None) as batch_op:
        batch_op.create_index('ix_exercises_name', ['name'], unique=False)

    op.create_table('training_profile',
    sa.Column('id', sa.TEXT(), nullable=False),
    sa.Column('sex', sa.String(length=10), nullable=False),
    sa.Column('birth_year', sa.Integer(), nullable=False),
    sa.Column('height_cm', sa.Numeric(precision=5, scale=2), nullable=False),
    sa.Column('current_weight_kg', sa.Numeric(precision=5, scale=2), nullable=False),
    sa.Column('experience_level', sa.String(length=20), nullable=False),
    sa.Column('training_days_per_week', sa.Integer(), nullable=False),
    sa.Column('session_duration_minutes', sa.Integer(), nullable=False),
    sa.Column('primary_goal', sa.String(length=30), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('training_profile', schema=None) as batch_op:
        batch_op.create_index('ix_training_profile_updated_at', ['updated_at'], unique=False)

    op.create_table('workout_plans',
    sa.Column('id', sa.TEXT(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('enabled', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('workout_plans', schema=None) as batch_op:
        batch_op.create_index('ix_workout_plans_enabled', ['enabled'], unique=False)
        batch_op.create_index('ix_workout_plans_name', ['name'], unique=False)

    op.create_table('exercise_alternatives',
    sa.Column('id', sa.TEXT(), nullable=False),
    sa.Column('exercise_id', sa.TEXT(), nullable=False),
    sa.Column('alternative_exercise_id', sa.TEXT(), nullable=False),
    sa.ForeignKeyConstraint(['alternative_exercise_id'], ['exercises.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['exercise_id'], ['exercises.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('exercise_id', 'alternative_exercise_id', name='uq_exercise_alternative')
    )
    op.create_table('plan_exercises',
    sa.Column('id', sa.TEXT(), nullable=False),
    sa.Column('plan_id', sa.TEXT(), nullable=False),
    sa.Column('exercise_id', sa.TEXT(), nullable=False),
    sa.Column('order_index', sa.Integer(), nullable=False),
    sa.Column('target_sets', sa.Integer(), nullable=True),
    sa.Column('target_reps', sa.Integer(), nullable=True),
    sa.Column('target_weight_mode', sa.String(length=20), nullable=False),
    sa.Column('fixed_weight', sa.Numeric(precision=6, scale=2), nullable=True),
    sa.Column('fixed_reps', sa.Integer(), nullable=True),
    sa.Column('rest_seconds', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['exercise_id'], ['exercises.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['plan_id'], ['workout_plans.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('plan_id', 'exercise_id', name='uq_plan_exercise')
    )
    with op.batch_alter_table('plan_exercises', schema=None) as batch_op:
        batch_op.create_index('ix_plan_exercises_order', ['order_index'], unique=False)
        batch_op.create_index('ix_plan_exercises_plan_id', ['plan_id'], unique=False)

    op.create_table('plan_schedules',
    sa.Column('id', sa.TEXT(), nullable=False),
    sa.Column('plan_id', sa.TEXT(), nullable=False),
    sa.Column('schedule_type', sa.String(length=20), nullable=False),
    sa.Column('interval_days', sa.Integer(), nullable=True),
    sa.Column('days_mask', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['plan_id'], ['workout_plans.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('plan_schedules', schema=None) as batch_op:
        batch_op.create_index('ix_plan_schedules_plan_id', ['plan_id'], unique=False)

    op.create_table('sessions',
    sa.Column('id', sa.TEXT(), nullable=False),
    sa.Column('plan_id', sa.TEXT(), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('started_at', sa.DateTime(), nullable=False),
    sa.Column('ended_at', sa.DateTime(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['plan_id'], ['workout_plans.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('sessions', schema=None) as batch_op:
        batch_op.create_index('ix_sessions_started_at', ['started_at'], unique=False)
        batch_op.create_index('ix_sessions_status', ['status'], unique=False)

    op.create_table('performed_exercises',
    sa.Column('id', sa.TEXT(), nullable=False),
    sa.Column('session_id', sa.TEXT(), nullable=False),
    sa.Column('exercise_id', sa.TEXT(), nullable=False),
    sa.Column('display_order', sa.Integer(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('is_skipped', sa.Boolean(), nullable=True),
    sa.Column('is_warmup', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['exercise_id'], ['exercises.id'], ),
    sa.ForeignKeyConstraint(['session_id'], ['sessions.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('performed_exercises', schema=None) as batch_op:
        batch_op.create_index('ix_performed_exercises_session', ['session_id'], unique=False)

    op.create_table('sets',
    sa.Column('id', sa.TEXT(), nullable=False),
    sa.Column('performed_exercise_id', sa.TEXT(), nullable=False),
    sa.Column('set_order', sa.Integer(), nullable=True),
    sa.Column('weight', sa.Numeric(precision=6, scale=2), nullable=False),
    sa.Column('reps', sa.Integer(), nullable=False),
    sa.Column('rpe', sa.Float(), nullable=True),
    sa.Column('rir', sa.Integer(), nullable=True),
    sa.Column('set_type', sa.String(length=20), nullable=False),
    sa.ForeignKeyConstraint(['performed_exercise_id'], ['performed_exercises.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('sets', schema=None) as batch_op:
        batch_op.create_index('ix_sets_performed_exercise', ['performed_exercise_id'], unique=False)
        batch_op.create_index('ix_sets_set_type', ['set_type'], unique=False)

    op.create_table('client_operations',
    sa.Column('operation_id', sa.TEXT(), nullable=False),
    sa.Column('operation_type', sa.String(length=50), nullable=False),
    sa.Column('resource_id', sa.TEXT(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('operation_id')
    )
    with op.batch_alter_table('client_operations', schema=None) as batch_op:
        batch_op.create_index('ix_client_operations_resource', ['resource_id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('sets', schema=None) as batch_op:
        batch_op.drop_index('ix_sets_set_type')
        batch_op.drop_index('ix_sets_performed_exercise')

    op.drop_table('sets')
    with op.batch_alter_table('performed_exercises', schema=None) as batch_op:
        batch_op.drop_index('ix_performed_exercises_session')

    op.drop_table('performed_exercises')
    with op.batch_alter_table('sessions', schema=None) as batch_op:
        batch_op.drop_index('ix_sessions_status')
        batch_op.drop_index('ix_sessions_started_at')

    op.drop_table('sessions')
    with op.batch_alter_table('plan_schedules', schema=None) as batch_op:
        batch_op.drop_index('ix_plan_schedules_plan_id')

    op.drop_table('plan_schedules')
    with op.batch_alter_table('plan_exercises', schema=None) as batch_op:
        batch_op.drop_index('ix_plan_exercises_plan_id')
        batch_op.drop_index('ix_plan_exercises_order')

    op.drop_table('plan_exercises')
    op.drop_table('exercise_alternatives')
    with op.batch_alter_table('workout_plans', schema=None) as batch_op:
        batch_op.drop_index('ix_workout_plans_name')
        batch_op.drop_index('ix_workout_plans_enabled')

    op.drop_table('workout_plans')
    with op.batch_alter_table('training_profile', schema=None) as batch_op:
        batch_op.drop_index('ix_training_profile_updated_at')

    op.drop_table('training_profile')
    with op.batch_alter_table('exercises', schema=None) as batch_op:
        batch_op.drop_index('ix_exercises_name')

    op.drop_table('exercises')
    # ### end Alembic commands ###
